---
title: "What distinguishes successful students?"
author: Will Landau
date: April 24, 2015
output: ioslides_presentation
---

```{r, echo=FALSE}
library(knitr)
knitr::knit_hooks$set(inline = as.character)
knitr::opts_chunk$set(cache=T, echo = F, results="hide", message=F)
knitr::opts_knit$set(eval.after = 'fig.cap')
```

```{r sources}
for(f in paste("../R/", c(
  "student",
  "issue",
  "subsets",
  "explore",
  "supervised"
), ".R", sep=""))
  source(f)
```


## Comb through the 2012 PISA data.

- Select highest 25\% and lowest 25\% of students based on reading and math scores.
- Response = high or low success.
- Which types of individual survey questions correlate with success?

## Matching coefficients

- Variables are grouped into key issues.

```{r usamatchissue}
plot.matching.by.issue()
```

## Salient issue becomes datasets to predict student success.

```{r usaerr}
err.plot()
```

## Other countries

```{r intlerr}
err.plot(countries = c("USA", "Japan", "Germany", "Peru"), facet.type = "Issue")
```
 
